services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'vnexpress'
      # MYSQL_DATABASE: 'news'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  go-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    # volumes:
    #   - ./app/.env.stg:/app/app/.env.stg
    environment:
      DB_USER: 'root'
      DB_PASSWORD: 'admin123'
      DB_HOST: 'db'
      # DB_NAME: 'news'
      DB_NAME: 'vnexpress'
      REDIS_HOST: 'redis'
      REDIS_PORT: '6379'

volumes:
  db_data:
